name: CI/CD DockerHub Auto Build & Push

on:
  push:
    branches: [ "main" ]

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'

      - name: Grant execute permission to gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew bootJar -x test

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: docker build -t kjunh972/dasom_memoreal:latest .

      - name: Push Docker image to DockerHub
        run: docker push kjunh972/dasom_memoreal:latest

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
            docker pull kjunh972/dasom_memoreal:latest
            docker stop dasom_memoreal || true
            docker rm dasom_memoreal || true
            docker run -d --name dasom_memoreal -p 8080:8080 kjunh972/dasom_memoreal:latest
            docker image prune -af

      - name: Notify Discord (배포 성공)
        if: success()
        run: |
          curl -H "Content-Type: application/json" \
            -d '{
              "embeds": [
                {
                  "color": 65280,
                  "title": "✅ 서버 배포 성공!",
                  "fields": [
                    {
                      "name": "Repository",
                      "value": "'"${GITHUB_REPOSITORY}"'",
                      "inline": true
                    },
                    {
                      "name": "Branch",
                      "value": "'"${GITHUB_REF##*/}"'",
                      "inline": true
                    }
                  ]
                }
              ]
            }' ${{ secrets.DISCORD_WEBHOOK }}

      - name: Notify Discord (배포 실패)
        if: failure()
        run: |
          curl -H "Content-Type: application/json" \
            -d '{
              "embeds": [
                {
                  "color": 16711680,
                  "title": "❌ 서버 배포 실패!",
                  "fields": [
                    {
                      "name": "Repository",
                      "value": "'"${GITHUB_REPOSITORY}"'",
                      "inline": true
                    },
                    {
                      "name": "Branch",
                      "value": "'"${GITHUB_REF##*/}"'",
                      "inline": true
                    }
                  ]
                }
              ]
            }' ${{ secrets.DISCORD_WEBHOOK }}
